# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ercc-peer0-org2
  namespace: hyperledger
  labels:
    app: ercc-peer0-org2
spec:
  selector:
    matchLabels:
      app: ercc-peer0-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ercc-peer0-org2
    spec:
      containers:
        - image: fpc/ercc
          name: ercc-peer0-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_PKG_ID
              valueFrom:
                configMapKeyRef:
                  name: chaincode-config
                  key: ercc-peer0-org2
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:9999"
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: ercc-peer0-org2
  namespace: hyperledger
  labels:
    app: ercc-peer0-org2
spec:
  ports:
    - name: grpc
      port: 9999
      targetPort: 9999
  selector:
    app: ercc-peer0-org2
